"""hey

Revision ID: 80ac49cd8c36
Revises: 
Create Date: 2022-09-12 20:08:51.051974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80ac49cd8c36'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_name', sa.String(), nullable=True),
    sa.Column('book_description', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('book_writer', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book_model')
    # ### end Alembic commands ###
